### ISSUE TITLE
Unusable from recent commits

### ISSUE THREAD

**Issue by m1foley** [mrtazz/simplenote.vim#101]
`:SimplenoteIndex` and `:SimplenoteUpdate` both give this error after I updated from `eb14cbe`:

```
Error detected while processing function simplenote#SimplenoteList:                                                                                                                          
line    4:                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                           
  File "<string>", line 1, in <module>                                                                                                                                                       
  File "/Users/mike/.vim/plugged/simplenote.vim/autoload/SimplenoteList.py", line 14, in <module>                                                                                            
    SimplenoteList()                                                                                                                                                                         
  File "/Users/mike/.vim/plugged/simplenote.vim/autoload/SimplenoteList.py", line 10, in SimplenoteList                                                                                      
    interface.list_note_index_in_scratch_buffer()                                                                                                                                            
  File "/Users/mike/.vim/plugged/simplenote.vim/autoload/SimplenoteUtilities.py", line 684, in list_note_index_in_scratch_buffer                                                             
    note_list, status = self.simplenote.get_note_list(since)                                                                                                                                 
  File "/Users/mike/.vim/plugged/simplenote.vim/autoload/simplenote.py/simplenote/simplenote.py", line 285, in get_note_list                                                                 
    if (len(tags) > 0):                                                                                                                                                                      
TypeError: object of type 'NoneType' has no len()                                                                                                                                            
```

---

Version info:

```
:version                                                                                                                                                                                     
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  6 2018 14:33:14)                                                                                                                           
macOS version                                                                                                                                                                                
Included patches: 1-280                                                                                                                                                                      
Compiled by Homebrew                                                                                                                                                                         
Huge version with MacVim GUI.  Features included (+) or not (-):                                                                                                                             
+acl               +clipboard         +dnd               +fullscreen        +listcmds          -mouse_sysmouse    +postscript        +statusline        +title             +windows          
+arabic            +cmdline_compl     -ebcdic            -gettext           +localmap          +mouse_urxvt       +printer           -sun_workshop      +toolbar           +writebackup      
+autocmd           +cmdline_hist      +emacs_tags        -hangul_input      +lua               +mouse_xterm       +profile           +syntax            +transparency      -X11              
+autochdir         +cmdline_info      +eval              +iconv             +menu              +multi_byte        -python            +tag_binary        +user_commands     -xfontset         
-autoservername    +comments          +ex_extra          +insert_expand     +mksession         +multi_lang        +python3           +tag_old_static    +vartabs           +xim              
+balloon_eval      +conceal           +extra_search      +job               +modify_fname      -mzscheme          +quickfix          -tag_any_white     +vertsplit         -xpm              
+balloon_eval_term +cryptv            +farsi             +jumplist          +mouse             +netbeans_intg     +reltime           +tcl               +virtualedit       -xsmp             
+browse            +cscope            +file_in_path      +keymap            +mouseshape        +num64             +rightleft         +termguicolors     +visual            -xterm_clipboard  
++builtin_terms    +cursorbind        +find_in_path      +lambda            +mouse_dec         +odbeditor         +ruby              +terminal          +visualextra       -xterm_save       
+byte_offset       +cursorshape       +float             +langmap           -mouse_gpm         +packages          +scrollbind        +terminfo          +viminfo                             
+channel           +dialog_con_gui    +folding           +libcall           -mouse_jsbterm     +path_extra        +signs             +termresponse      +vreplace                            
+cindent           +diff              -footer            +linebreak         +mouse_netterm     +perl              +smartindent       +textobjects       +wildignore                          
+clientserver      +digraphs          +fork()            +lispindent        +mouse_sgr         +persistent_undo   +startuptime       +timers            +wildmenu                            
   system vimrc file: "$VIM/vimrc"                                                                                                                                                           
     user vimrc file: "$HOME/.vimrc"                                                                                                                                                         
 2nd user vimrc file: "~/.vim/vimrc"                                                                                                                                                         
      user exrc file: "$HOME/.exrc"                                                                                                                                                          
  system gvimrc file: "$VIM/gvimrc"                                                                                                                                                          
    user gvimrc file: "$HOME/.gvimrc"                                                                                                                                                        
2nd user gvimrc file: "~/.vim/gvimrc"                                                                                                                                                        
       defaults file: "$VIMRUNTIME/defaults.vim"                                                                                                                                             
    system menu file: "$VIMRUNTIME/menu.vim"                                                                                                                                                 
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"                                                                                                                      
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1               
Linking: clang   -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoo
t/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Dev
eloper/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SD
Ks/MacOSX10.13.Internal.sdk/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -fsta
ck-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3
.7m -framework CoreFoundation -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby                                                                          
```

**Comment by atomicules** [comment]
Interesting... thanks for letting me know. I shall take a look.

Looks like I still have a rogue `since` knocking about.

**Comment by atomicules** [comment]
@m1foley Can you please try [the release](https://github.com/mrtazz/simplenote.vim/releases/tag/v2.0.2) I've just pushed?

If you are still having issues can you provide a bit more info on what's going on? Does nothing work? Is it certain notes it's struggling with? 

I'll check it's not a Python3 thing in the meantime...

**Comment by atomicules** [comment]
I still had a build of vim knocking about with Python 3.4 and a quick check with that proved ok.

**Comment by m1foley** [comment]
Verified the latest code works now. Thanks again for his life-changing plugin!
