### ISSUE TITLE
Unable to list notes with SimplenoteList

### ISSUE THREAD

**Issue by Blatant22** [mrtazz/simplenote.vim#91]
Hi, since upgrading to `1.3.1` receive the following error when trying to list notes (`$HOME` personally entered):
```vim
"Simplenote" [New File]                                                                                                                   
Error detected while processing function simplenote#SimplenoteList:                                                                       
line    4:                                                                                                                                
Traceback (most recent call last):                                                                                                        
  File "<string>", line 1, in <module>                                                                                                    
  File "$HOME/.dotfiles/.vim/plugged/simplenote.vim/autoload/SimplenoteList.py", line 14, in <module>                               
    SimplenoteList()                                                                                                                      
  File "$HOME/.dotfiles/.vim/plugged/simplenote.vim/autoload/SimplenoteList.py", line 10, in SimplenoteList                         
    interface.list_note_index_in_scratch_buffer()                                                                                         
  File "$HOME/.dotfiles/.vim/plugged/simplenote.vim/autoload/SimplenoteUtilities.py", line 565, in list_note_index_in_scratch_buffer
    note_titles = [self.format_title(n) for n in notes]                                                                                   
  File "$HOME/.dotfiles/.vim/plugged/simplenote.vim/autoload/SimplenoteUtilities.py", line 565, in <listcomp>                       
    note_titles = [self.format_title(n) for n in notes]                                                                                   
  File "$HOME/.dotfiles/.vim/plugged/simplenote.vim/autoload/SimplenoteUtilities.py", line 235, in format_title                     
    padding = " " * (max_tleft_len - tleft_len)                                                                                           
TypeError: can't multiply sequence by non-int of type 'float'                                                                             
```
This error is consistent on `Ubuntu-16.04` and `macOS 10.12` platforms; both are using `python3`.

**Comment by skegel13** [comment]
I get this same issue using Linux Mint 17, however, I do not get it using Windows 10.

**Comment by atomicules** [comment]
Thanks for letting me know. I'll try to re-check the python 3 compatibility. I didn't think I'd broken anything there, but perhaps I did.

**Comment by atomicules** [comment]
Sorry for the delay. Snowed under with stuff at the moment. 

Fixed, but I don't understand why that wasn't an issue before because it should have been.

**Comment by Blatant22** [comment]
Absolutely no worries; had frozen the release at commit `8e9bcb8` so was no consequence for continued use. 

Thanks for the fix, and bigger thanks for developing this fantastic (and essential) enhancement to my Vim workflow.
